### ISSUE TITLE
decode_boxes方法中，为什么要除以4

### ISSUE THREAD

**Issue by EragonYin** [bubbliiiing/faster-rcnn-tf2#10]
https://github.com/bubbliiiing/faster-rcnn-tf2/blob/b2383af9fdf9fb73ce7bbd4f9b3f79f65b271e52/utils/utils.py#L152

```
        # 真实框距离先验框中心的xy轴偏移情况
        decode_bbox_center_x = mbox_loc[:, 0] * prior_width / 4
        decode_bbox_center_x += prior_center_x
        decode_bbox_center_y = mbox_loc[:, 1] * prior_height / 4
        decode_bbox_center_y += prior_center_y
        
        # 真实框的宽与高的求取
        decode_bbox_width = np.exp(mbox_loc[:, 2] / 4) # 此处为什么要乘以指数
        decode_bbox_width *= prior_width
        decode_bbox_height = np.exp(mbox_loc[:, 3] / 4) # 此处为什么要乘以指数
        decode_bbox_height *= prior_height
```

**Comment by bubbliiiing** [comment]
改变数量级

**Comment by EragonYin** [comment]
up主 opencv的frcnn的应用你了解不？就是opencv使用tf训练好的模型就能进行目标检测，但关于网上但文章中，opencv需要额外加载pbtxt文件。pbtxt文件的生成，说是要训练时相关的.config文件，这方面的问题我找了很多资料，都没导致config文件和项目的关系..

**Comment by EragonYin** [comment]
参考文章：https://www.aiuai.cn/aifarm967.html

**Comment by bubbliiiing** [comment]
这个我不太了解，不太用opencv的frcnn

**Comment by EragonYin** [comment]
我扒了一天的网..终于了解到关于config文件构建神经网络的相关内容。它是源自于[Tensorflow官方项目](https://github.com/tensorflow/models)，官方提供了很多已经设计好的[配置文件](https://github.com/tensorflow/models/tree/master/research/object_detection/configs/tf2)，直接使用就能构建神经网络及训练过程，唯一不好的点就是项目依赖太多，最好要在官方项目文件夹下直接搭建项目及训练。最后，训练出来的 pb模型文件 配合.config文件生成 .pbtxt 文件，然后在opencv项目中直接使用了
```python
source = cv.imread("xxx.jpg", cv.IMREAD_COLOR)
model = cv.dnn.readNetFromTensorflow('xx.pb', 'xx.pbtxt') # 加载模型
img = cv.dnn.blobFromImage(source, size=(100, 100))
model.setInput(img) 
output = model.forward()  # 输出预测结果
```
up主有兴趣可以研究一波，这种方式挺适合跨平台

**Comment by EragonYin** [comment]
[tensorflow使用object detection API 参考文章1](https://www.cnblogs.com/Jason66661010/p/12789043.html)
[tensorflow使用object detection API 参考文章2-1](https://blog.csdn.net/m0_37407756/article/details/80810364)
[tensorflow使用object detection API 参考文章2-2](https://blog.csdn.net/m0_37407756/article/details/80842924)
[opencv使用tensorflow模型进行目标检测](https://www.aiuai.cn/aifarm967.html)

**Comment by bubbliiiing** [comment]
我其实想研究onnx，但是没什么好参考的资料

**Comment by EragonYin** [comment]
我这两天也了解个清楚了, object detection api还有其他的局限性，tensorflow兼容了tf1和tf2，但在opencv中使用object detection，要使用tf1中graph相关api转出来的模型  :( ，这就导致了tf版本兼容的问题。opencv的相关[issue](https://github.com/opencv/opencv/issues/19257)中也提到了使用onnx模型来解决这个问题

**Comment by bubbliiiing** [comment]
这玩意真的挺难搞
